#!/bin/bash

# Copyright 2019-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Shengzhou Liu <shengzhou.liu@nxp.com>

# Runtime Dynamic Configuration for single distro image on various NXP i.MX/Layerscape platforms.

set -e

soc=$(tr -d '.' < /sys/devices/soc0/soc_id | tr 'A-Z' 'a-z')

if [ $soc != imx8mp ]; then
    rm -f /etc/systemd/system/multi-user.target.wants/imx8-isp.service
fi

# vpu hantro daemon
if [ $soc = imx8mp ]; then
    ln -sf vsidaemon-IMX8MP /usr/bin/vsidaemon
    rm -f /etc/systemd/system/multi-user.target.wants/firmwared.service
elif [ $soc = imx8mq ]; then
    ln -sf vsidaemon-IMX8MQ /usr/bin/vsidaemon
elif [ $soc = imx8mm ]; then
    ln -sf vsidaemon-IMX8MM /usr/bin/vsidaemon
    ln -sf libg2d-viv-mx8mm.so.2.2.0 /usr/lib/libg2d.so.2
elif [ $soc = imx8qm -o $soc = imx8qxp ]; then
    if [ -e /usr/lib/libg2d-dpu.so.2.2.0 ]; then
	ln -sf libg2d-dpu.so.2.2.0 /usr/lib/libg2d.so.2
    fi
elif [ $soc = imx93 ]; then
    ln -sf libg2d-pxp.so.2.2.0 /usr/lib/libg2d.so.2
fi

if [ $soc = imx8qm -o $soc = imx8qxp ] && [ ! -L /lib/firmware/amphion/vpu ]; then
    cp -r /lib/firmware/imx/vpu /lib/firmware/amphion/
fi

if [ $desktop = gnome ] && [ $soc = imx91 -o $soc = imx93 ] && [ -f /usr/lib/libGLESv2.so ]; then
    rm -f /usr/lib/{libGLESv2.so*,libEGL.so*,libcogl.so*,libgstallocators-1.0.so,libvulkan.so}
    rm -f /usr/lib/{libdrm.so*,libgbm.so*,libgbm_viv.so}
    rm -f /usr/lib/libclutter-gst-3.0.so*
fi

# fmc service only for DPAA on ls1043/ls1046
if [ $soc != ls1043a -a $soc != ls1046a ]; then
    rm -f /etc/systemd/system/multi-user.target.wants/fmc.service
fi
