RECOVERY_SD_GENIMAGE_CFG="$(cat <<CFG
# -------------------------------------------------------------------
# Recovery SD‑card image with bootloader + ext4 rootfs
# -------------------------------------------------------------------
image recovery-sd.img {
    hdimage {
        partition-table-type = "mbr"
    }

    size = 8600M

    partition bootloader {
        in-partition-table = "no"
        image              = "${FLASH_BIN}"
        offset             = ${DISK_BOOTLOADER_OFFSET}
    }

    partition boot {
        in-partition-table = "true"
        partition-type = 0xC
        image = "boot.vfat"
        bootable = true
        size = 64M
    }

    partition rootfs {
        partition-type = 0x83
        image          = "rootfs.ext4"
    }
}

image boot.vfat {
   vfat {
      label = "boot"
   }
   size = 64M
   srcpath = "$RECOVERY_SDCARD_BOOTDIR"
}

# build the ext4 filesystem image from your directory
image rootfs.ext4 {
    ext4 {
        label       = "rootfs"
        use-mke2fs  = "yes"
    }
    srcpath = "$RECOVERY_SDCARD_RFSDIR"
    size    = 8400M
}
CFG
)"
