# [general]
machine=imx7-var-som

MACHINE_LIST="imx7-var-som"

KERNEL_DEVICETREE=" \
	nxp/imx/imx7d-var-som-emmc-m4-wm8731.dtb \
	nxp/imx/imx7d-var-som-emmc-m4.dtb \
	nxp/imx/imx7d-var-som-emmc-wm8731.dtb \
	nxp/imx/imx7d-var-som-emmc.dtb \
	nxp/imx/imx7d-var-som-nand-m4-wm8731.dtb \
	nxp/imx/imx7d-var-som-nand-m4.dtb \
	nxp/imx/imx7d-var-som-nand-wm8731.dtb \
	nxp/imx/imx7d-var-som-nand.dtb \
"

NXP_WLAN_BT="true"
FIRMWARE_WL18XX="true"
IW612_UTILS="false"
CONNECTIVITY_OPENTHREAD="false"
CONNECTIVITY_OPENTHREAD_IWXXX_SPI="false"

SCFW_SUPPORT="false"
ISP_VVCAM_MODULE="false"

UTILS_FIRMWARED="false"
UTILS_IMX_TEST="false"

UBOOT_CONFIG="mx7dvar_som_defconfig"
UBOOT_IMX_BINARY="u-boot-with-spl.imx"

COMPOSITE_IMG1_FILE_sd="bsp/u-boot/imx7-var-som/output/mx7dvar_som_defconfig/${UBOOT_IMX_BINARY}"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-bootpartition-genconfig.conf"

# offset 1K
DISK_BOOTLOADER_OFFSET="1K"

# Disable FreeRTOS support
FREERTOS_SUPPORT="false"

# Recovery SD Card Configuration
INSTALL_DEBIAN_ECHOS="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/45a234c9d9d31593795a9232b54340286b6179b9/scripts/var_mk_yocto_sdcard/variscite_scripts/echos.sh"
INSTALL_DEBIAN_TARGET_BOOT="u-boot-with-spl.imx"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"
