# [general]
machine=imx95-var-dart

MACHINE_LIST="imx95-var-dart"

KERNEL_DEVICETREE=" \
    freescale/imx95-var-dart-dt8mcustomboard.dtb \
    freescale/imx95-var-dart-dt8mcustomboard-m7.dtb \
    freescale/imx95-var-dart-sonata.dtb \
    freescale/imx95-var-dart-sonata-m7.dtb \
"

# Disable G2D
ENABLE_G2D="false"
WESTON_RENDER="pixman"

UBOOT_CONFIG="imx95_var_dart_defconfig"

IMX_MKIMAGE_DTBS="imx95-var-dart-dt8mcustomboard.dtb"
IMX_MKIMAGE_TARGET="flash_a55"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx95-var-dart/flash.bin"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-genconfig.conf"

# Disable bcm43xx support
BCM43XX_UTILS="false"

# Disable FreeRTOS support
FREERTOS_SUPPORT="false"

# Disable isp vvcam
export ISP_VVCAM_MODULE="false"

export CONFIG_IMX_TEST="false"

# offset 32k
DISK_BOOTLOADER_OFFSET="32768"

# Recovery SD Card Configuration
INSTALL_DEBIAN_SCRIPT="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/mx8_install_yocto.sh"
INSTALL_DEBIAN_ECHOS="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/echos.sh"
INSTALL_DEBIAN_TARGET_BOOT="imx-boot-sd.bin"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"
