name: Git Push Workflow Actions

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-flexbuild:
    strategy:
      matrix:
        machine:
          - imx6ul-var-dart
        rootfs:
          - desktop
    uses: varigit-dev/action-workflows/.github/workflows/flexbuild.yml@dev_flexbuild
    with:
      flexbuild-ref: ${{ github.sha }}
      debian-version: 12
      debian-version-name: bookworm
      machine: ${{ matrix.machine }}
      rootfs: ${{ matrix.rootfs }}

    secrets:
      DO_SPACES_KEY:     ${{ secrets.DO_SPACES_KEY }}
      DO_SPACES_SECRET:  ${{ secrets.DO_SPACES_SECRET }}
      DO_SPACES_ENDPOINT: ${{ secrets.DO_SPACES_ENDPOINT }}
